name:  Parse and Sort CSV App (Staging)

on:
  push:
   branches: ['staging']

  pull_request:
    branches: ['staging']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18]
    steps:
      - uses: actions/checkout@v2
      - name: Set up node ${{matrix.node_version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run Build
        run: npm run build



  